version: '3.9'
services:
  app_server:
    restart: on-failure
    build: ./server
    ports: 
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
    - ./nginx/html:/var/www/public_html
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - app_server
